load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_library")

package(default_visibility = ["//visibility:public"])

cpp_proto_library(
    name = "storage_service_proto",
    protos = [
        "storage_service.proto",
    ],
    with_grpc = True,
)