git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf.git",
    commit = "35f4ff08da86cdfa24cb1ce274cec6bfc1d43dc2",
)

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

git_repository(
    name = "gtest",
    remote = "https://github.com/google/googletest.git",
    commit = "077ee54cefd247656ac9a995e150e0d1ab9d0bf7",
)

git_repository(
    name = "gflags",
    remote = "https://github.com/gflags/gflags.git",
    commit = "660603a3df1c400437260b51c55490a046a12e8a",
)

http_archive(
    name = "com_github_gflags_gflags",
    sha256 = "6e16c8bc91b1310a44f3965e616383dbda48f83e8c1eaa2370a215057b00cabe",
    strip_prefix = "gflags-77592648e3f3be87d6c7123eb81cbad75f9aef5a",
    urls = [
        "https://mirror.bazel.build/github.com/gflags/gflags/archive/77592648e3f3be87d6c7123eb81cbad75f9aef5a.tar.gz",
        "https://github.com/gflags/gflags/archive/77592648e3f3be87d6c7123eb81cbad75f9aef5a.tar.gz",
    ],
)

git_repository(
		name = "glog",
		remote = "https://github.com/google/glog.git",
		commit = "8d7a107d68c127f3f494bb7807b796c8c5a97a82"
)