git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf.git",
    commit = "35f4ff08da86cdfa24cb1ce274cec6bfc1d43dc2",
)

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

git_repository(
    name = "gtest",
    remote = "https://github.com/google/googletest.git",
    commit = "077ee54cefd247656ac9a995e150e0d1ab9d0bf7",
)